In [77]:
import os
import pandas
import numpy
import math
import matplotlib.pyplot as plt

##### **Tipos de dados**
**Dados númericos**

In [10]:
a = 1
b = 1.0
c = int(b)

print(f'Valor da variável a: {a} ( {type(a)}). \nValor da variável b: {b} ({type(b)}). \nValor da variável c: {c} ({type(c)}).')

Valor da variável a: 1 ( <class 'int'>). 
Valor da variável b: 1.0 (<class 'float'>). 
Valor da variável c: 1 (<class 'int'>).


<i>Operações com Not a number (NaN)</i>

In [17]:
d = numpy.nan
print(f'Valor da variável d: {d} ( {type(d)}).')
print(f'Multiplicação por escalar: {d*1} \nSoma com escalar: {d+1} \nSoma pelo Numpy: {numpy.nansum([d,1])}')

Valor da variável d: nan ( <class 'float'>).
Multiplicação por escalar: nan 
Soma com escalar: nan 
Soma pelo Numpy: 1.0


**Strings**

In [21]:
f = 'Fábio'
g = 'Gabriel'
print(f'{f} e {g}. \nSoma de strings: {f + g}.\nSoma de strings: {f} {g}.')

Fábio e Gabriel. 
Soma de strings: FábioGabriel.
Soma de strings: Fábio Gabriel.


**Booleanos**

<i>Valores booleanos: True or False</i>

In [24]:
a == 1
a == 1
x = (a==1)
y = (a==2)

print(f'Valor booleano da variável h: {x} ( {type(x)}).')
print(f'Valor booleano da variável h: {y} ( {type(y)}).')

Valor booleano da variável h: True ( <class 'bool'>).
Valor booleano da variável h: False ( <class 'bool'>).


<i>Diferença entre armazenamento de booleanos ou strings</i>

In [25]:
i = True
ii = 'True'
print(type(i))
print(type(ii))

<class 'bool'>
<class 'str'>


<i>Booleanos em operações matemáticas</i>

In [27]:
print(a==b)
print(a!=b)
print(a>b)
print(a>=b)

True
False
False
True


##### **Operações Matemáticas**

É recomendado não usar os caracteres <i>'l', 'O' ou 'I'</i> como nomes de variáveis, pois podem ser confundidos com os números um e zero.

In [44]:
print(f'Soma de valores númericos: {a+b}')
ab = a + b
j = a*b
k = a/b
m = 5**3

print(f'Soma de valores númericos: {ab}')
print(f'Multiplicação de valores númericos: {j}')
print(f'Divisão de valores númericos: {k}')
print(f'Potência de valores númericos: {m :.1f}')


Soma de valores númericos: 2.0
Soma de valores númericos: 2.0
Multiplicação de valores númericos: 1.0
Divisão de valores númericos: 1.0
Potência de valores númericos: 125.0


<i>Biblioteca de suporte Math</i> 

In [52]:
#Calculate the exponential function of various numbers using 'e' as the base
print(round(math.exp(10),2))
print(round(math.exp(0),2))
print(round(math.exp(a),2))
print(round(math.exp(-10),2))
print(5*'-')
#Calculate the log function 
print(round(math.log(c),2))
print(round(math.log10(100),2))

22026.47
1.0
2.72
0.0
-----
0.0
2.0


##### **Listas**

In [65]:
list = [1,2,True,4,5,'a']
print(f'Tamanho da lista: {len(list)}')
print(f'Primeiro elemento: {list[0]}')
print(f'Último elemento: {list[-1]}')
list

Tamanho da lista: 6
Primeiro elemento: 1
Último elemento: a


[1, 2, True, 4, 5, 'a']

<i>Verificação Booleana</i>

In [62]:
print(list == a)
print(list[0] == a)

False
True


<i>Tipagem em listas</i>

In [73]:
list2 = [1,a,'c']
print(type(list2))
for i in range(len(list2)):
    print(f'{i}ª Elemento: {type(list2[i])}')
list2

<class 'list'>
0ª Elemento: <class 'int'>
1ª Elemento: <class 'int'>
2ª Elemento: <class 'str'>


[1, 1, 'c']

##### **Filepaths**

In [79]:
filepath = 'c:/Users/Hydroinfo/Documents/Scripts/Modelling_air/Air-Modelling'
filepath_r = r'c:\Users\Hydroinfo\Documents\Scripts\Modelling_air\Air-Modelling'
print(filepath)
print(filepath_r)

c:/Users/Hydroinfo/Documents/Scripts/Modelling_air/Air-Modelling
c:\Users\Hydroinfo\Documents\Scripts\Modelling_air\Air-Modelling


<i>Listagem dos arquivos no diretório especificado</i>

In [101]:
print(os.listdir(filepath))
print(os.listdir(filepath)[0])
print(filepath + '/' + os.listdir(filepath)[0])
print(os.listdir(filepath + '/' + os.listdir(filepath)[0]))
print(f'Diretório atual: {os.getcwd()}')

['.git', '.gitignore', 'documents', 'excel', 'figures', 'rasters', 'results', 'scripts', 'shapefiles', 'venv']
.git
c:/Users/Hydroinfo/Documents/Scripts/Modelling_air/Air-Modelling/.git
['config', 'description', 'FETCH_HEAD', 'HEAD', 'hooks', 'index', 'info', 'logs', 'objects', 'packed-refs', 'refs']
Diretório atual: c:\Users\Hydroinfo\Documents\Scripts\Modelling_air\Air-Modelling


<i>Mudança de diretório</i>

In [130]:
os.chdir(r'c:\Users\Hydroinfo\Documents\Scripts')
new_filepath = os.getcwd()
print(new_filepath)
print(os.listdir(new_filepath))

c:\Users\Hydroinfo\Documents\Scripts
['Automação Metocean', 'Extreme Values Analysis', 'Hidrology', 'Modelling_air', 'Modelo de Calibração', 'projection_3d.ipynb']


<i>Criação de diretório</i>

In [128]:
new_path = os.getcwd() + '\\' + 'test2'
print(new_path)

if os.path.isdir(new_path):
    print('Diretório existente!')
    with open(new_path + '\\copy.txt', 'w') as file:
        file.write(':)')
else:
    print('Criando diretório...')
    os.mkdir(new_path)
    with open(new_path + '\\copy.txt', 'w') as file:
        file.write(':)')

c:\Users\Hydroinfo\Documents\Scripts\test2
Criando diretório...


##### **Arrays e Dataframes**

<i>Introdução aos arrays</i>

In [142]:
list = [round(num,2) for num in range(0,20)]
n = numpy.array(list)
print(f'Dimensões do array: {n.shape}')
print(f'Tipo de variável: {type(n)}')
print(n)

<class 'numpy.ndarray'>
Dimensões do array: (20,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


<i>Criação de matrizes de números aleatórios</i>

In [166]:
n = numpy.random.rand(4,6)
n =  numpy.around(n,2)
print(f'Dimensões do array: {n.shape}')
n

Dimensões do array: (4, 6)


array([[0.19, 0.02, 0.57, 0.84, 0.66, 0.29],
       [0.72, 0.25, 0.36, 0.74, 0.26, 0.54],
       [0.17, 0.85, 0.94, 0.9 , 0.45, 0.89],
       [0.04, 0.31, 0.98, 0.87, 0.24, 0.19]])

<i>Acessando arrays</i>

In [174]:
for c in range(n.shape[1]):
    print(f'{c+1}ª Coluna: {n[:,c]}')

print(5*'-')
for c in range(n.shape[0]):
    print(f'{c+1}ª Linha: {n[c,:]}')

1ª Coluna: [0.19 0.72 0.17 0.04]
2ª Coluna: [0.02 0.25 0.85 0.31]
3ª Coluna: [0.57 0.36 0.94 0.98]
4ª Coluna: [0.84 0.74 0.9  0.87]
5ª Coluna: [0.66 0.26 0.45 0.24]
6ª Coluna: [0.29 0.54 0.89 0.19]
-----
1ª Linha: [0.19 0.02 0.57 0.84 0.66 0.29]
2ª Linha: [0.72 0.25 0.36 0.74 0.26 0.54]
3ª Linha: [0.17 0.85 0.94 0.9  0.45 0.89]
4ª Linha: [0.04 0.31 0.98 0.87 0.24 0.19]


In [185]:
#Resgate de linha 
print(n[0,:])
print(5*'-')
#Resgate de coluna 
print(n[:,0])
print(5*'-')
#Resgate de colunas desejadas
print(n[:,0:2])
print(5*'-')
#Resgate de linhas desejadas
print(n[-1,:])
print(5*'-')
#Resgate do primeiro valor da última coluna
print(n[0,-1])

[0.19 0.02 0.57 0.84 0.66 0.29]
-----
[0.19 0.72 0.17 0.04]
-----
[[0.19 0.02]
 [0.72 0.25]
 [0.17 0.85]
 [0.04 0.31]]
-----
[0.04 0.31 0.98 0.87 0.24 0.19]
-----
0.29


<i>Aplicando logaritmo</i>

In [187]:
an = numpy.log(n*5)
an =  numpy.around(an,2)
an

array([[-0.05, -2.3 ,  1.05,  1.44,  1.19,  0.37],
       [ 1.28,  0.22,  0.59,  1.31,  0.26,  0.99],
       [-0.16,  1.45,  1.55,  1.5 ,  0.81,  1.49],
       [-1.61,  0.44,  1.59,  1.47,  0.18, -0.05]])